name: ziroom

on:
  schedule:
    - cron: '0 0 1/7 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: Auto Checkin
      env:
        EMAIL_COUNT: ${{secrets.EMAIL_COUNT}}
        EMAIL_PSW: ${{secrets.EMAIL_PSW}}
        EMAIL_RECEIVE: ${{secrets.EMAIL_RECEIVE}}
      run:
        python ZiroomCrawler.py
